[package]
name = "qc"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
bumpalo = "3.12"
logos = "0.13"
tinyvec = { version = "1.6", features = ["rustc_1_57"] }

[profile.release]
debug = true
